openapi: 3.0.0
info:
  title: Auth API
  version: 1.0.0
  description: API для регистрации и авторизации пользователей
tags:
  - name: Auth
    description: Операции с пользователями
paths:
  /auth/register:
    post:
      summary: Регистрация пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "user123"
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "securepassword"
      responses:
        "201":
          description: Пользователь зарегистрирован
        "400":
          description: Ошибка валидации или пользователь уже существует
        "500":
          description: Внутренняя ошибка сервера

  /auth/login:
    post:
      summary: Авторизация пользователя
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  example: "user@example.com"
                password:
                  type: string
                  format: password
                  example: "securepassword"
      responses:
        "200":
          description: Успешный вход, возвращает токен
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      username:
                        type: string
                      email:
                        type: string
                      isAdmin:
                        type: boolean
        "400":
          description: Неверные учетные данные
        "500":
          description: Внутренняя ошибка сервера
