openapi: 3.0.0
info:
  title: Project API
  version: 1.0.0
  description: API for managing projects
tags:
  - name: Projects
    description: Operations with projects
paths:
  /projects:
    post:
      summary: Create a project
      tags:
        - Projects
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                link:
                  type: string
                title:
                  type: string
                desc:
                  type: string
      responses:
        "201":
          description: Project created
        "400":
          description: Validation error
    get:
      summary: Get all projects
      tags:
        - Projects
      responses:
        "200":
          description: All projects retrieved successfully

  /projects/{id}:
    get:
      summary: Get a project by ID
      tags:
        - Projects
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Project found
        "404":
          description: Project not found

    put:
      summary: Update a project
      tags:
        - Projects
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
                link:
                  type: string
                title:
                  type: string
                desc:
                  type: string
      responses:
        "200":
          description: Project updated
        "400":
          description: Validation error
        "404":
          description: Project not found

    delete:
      summary: Delete a project
      tags:
        - Projects
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Project deleted
        "404":
          description: Project not found
