openapi: 3.0.0
info:
  title: Student API
  version: 1.0.0
  description: API for managing students
tags:
  - name: Students
    description: Operations with students
paths:
  /students:
    post:
      summary: Create a student
      tags:
        - Students
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                coins:
                  type: integer
                email:
                  type: string
                birthdate:
                  type: string
                  format: date
                phoneNumber:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        "201":
          description: Student successfully created
        "400":
          description: Validation error
    get:
      summary: Get all students
      tags:
        - Students
      responses:
        "200":
          description: Successfully retrieved all students

  /students/{id}:
    get:
      summary: Get a student by ID
      tags:
        - Students
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Student successfully found
        "404":
          description: Student not found

    put:
      summary: Update a student
      tags:
        - Students
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                coins:
                  type: integer
                email:
                  type: string
                birthdate:
                  type: string
                  format: date
                phoneNumber:
                  type: string
      responses:
        "200":
          description: Student updated successfully
        "400":
          description: Validation error
        "404":
          description: Student not found

    delete:
      summary: Delete a student
      tags:
        - Students
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Student deleted successfully
        "404":
          description: Student not found
